import "./globals.css";
import { CartProvider } from "@/components/context/CartContext";
import Header from "@/components/Header";

export const metadata = {
  title: "coffee shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header />
          <div className="mt-10">
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
