import "./globals.css";
import { CartProvider } from "@/components/context/CartContext";

export const metadata = {
  title: "coffee shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
        {children}
        </CartProvider>
      </body>
    </html>
  );
}
